version: '3'
services:

  node1:
    build: ./server
    depends_on:
      - mysql1
    container_name: s1
    ports:
      - "80:8080"
    volumes:
      - ./server:/usr/src/app

  mysql1:
    image: mysql:5.7.31
    container_name: db1
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: cbo_db
    volumes:
    - ./sql:/var/lib/mysql
